version: '2'
services:
  wiremock:
    image: wiremock/wiremock
    container_name: kronika-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
volumes:
  files:
  mappings: